appConfig:
  general:
    localIP: 192.168.2.29
    port: 3333
    dmlPort: 4444
    agentPort: 3333
  nfs:
    subnet: 192.168.2.0/24
  emulator:
    images:
      dml:1.0:
        dockerfile: dml_app/Dockerfile
        requirements: dml_app/dml_req.txt
  physical:
    requirements: dml_app/dml_req.txt
  hosts:
    3990x:
      ip: 192.168.2.4
  nodes:
    n1:
      type: emulator
      host: 3990x
      dockerGroups:
        master:
          containers: 1   # node named n1-master-1
          memory: 2G
          cpu: 2
          nic: eth0
          image: dml:1.0
          cmd: python3 pr_sgd_master_new.py -p $dmlPort
          volumes:
            dml_file:
              hostPath: ./dml_file
              nodePath: /home/worker/dml_file
          ports:
            rule: sequential
            begin: 8001
        worker:
          containers: 8   # nodes named n1-worker-1, n1-worker-2, etc.
          memory: 2G      # each
          cpu: 2          # each
          nic: eth0
          image: dml:1.0
          cmd: python3 pr_sgd_worker_new.py -p $dmlPort
          volumes:
            dml_file:
              hostPath: ./dml_file
              nodePath: /home/worker/dml_file
          # make sure the ports won't conflict.
          ports:
            rule: sequential
            begin: 8002
  links:
    - n1-master-1 n1-worker* 10 mbps
    - n1-worker* n1-master-1 random 200 500 mbps
